# image repo https://github.com/confluentinc/cp-docker-images
# create topic: docker run --net=host --rm confluentinc/cp-kafka:5.0.0 kafka-topics --create --topic foo --partitions 4 --replication-factor 2 --if-not-exists --zookeeper localhost:32181

version: '3'
services:
  zk1:
    image: confluentinc/cp-zookeeper:5.0.0
    container_name: zk1
    restart: always
    healthcheck:
      test: echo stat | nc localhost 22181
      interval: 10s
      timeout: 10s
      retries: 3
    ports: 
      - "22181:22181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:22888:23888
    volumes:
      - ./kafka/zk1/data:/var/lib/zookeeper/data
      - ./kafka/zk1/log:/var/lib/zookeeper/log

  kafka1:
    image: confluentinc/cp-kafka:5.0.0
    container_name: kafka1
    restart: always
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    ports:
      - "19092:19092"
    depends_on:
      - zk1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${MY_IP}:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${MY_IP}:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./kafka/kafka1/data:/var/lib/kafka/data
